stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  before_script:
      - cargo install wasm-pack
  script:
    - cargo build --all --verbose
    - cargo test --all --verbose
  allow_failure: true

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  before_script:
      - cargo install wasm-pack
      - apt install -y firefox
      - curl --retry 5 -LO https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
      - tar xf geckodriver-v0.24.0-linux64.tar.gz
  script:
    - cargo build --all --verbose
    - cargo test --all --verbose
    - GECKODRIVER=$(pwd)/geckodriver ./test.sh
