[package]
name = "caesar"
version = "0.1.0"
authors = ["lee"]
edition = "2018"

[dependencies]
browser = { path = "crates/browser" }

[workspace]
members = [
    "crates/vdom",
    "crates/browser",
    "crates/browser/examples/simple_app",
    "examples/isomorphic/client",
]

exclude = [
    "crates/ui-orbtk",
]

