[package]
name = "sauron-native"
version = "0.1.0"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "MIT"
description = "Truly native, truly cross platform GUI framework for rust"
repository = "https://github.com/ivanceras/sauron-native"
documentation = "https://docs.rs/sauron-native"
readme = "README.md"
keywords = ["html", "dom", "web"]
edition = "2018"

[dependencies]
sauron = { version = "0.21.0", optional = true }
sauron_vdom = "0.21.0"
itui = { path = "crates/itui", optional = true }
termion = { version = "1.5", optional= true }
wasm-bindgen = { version = "0.2.42", optional = true }
gtk = { version = "0.6.0", optional = true }
gio = { version = "0.6.0", optional = true }
glib = { version = "0.7.0", optional = true }

[dependencies.web-sys]
version = "0.3.19"
optional = true
features = [
    "Comment",
    "console",
    "Document",
    "Element",
    "Event",
    "HtmlElement",
    "EventTarget",
    "KeyboardEvent",
    "InputEvent",
    "HtmlCollection",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "MouseEvent",
    "Node",
    "NodeList",
    "Text",
    "CharacterData",
    "Performance",
    "Window",
]

[dev-dependencies]
stderrlog = "0.4"
rand = "0.6"
failure = "0.1"
structopt = "0.2"
wasm-bindgen-test = "0.2.33"
cfg-if = "0.1.7"



[features]
with-tui = ["itui", "termion"]
with-html = ["sauron", "web-sys", "wasm-bindgen"]
with-gtk = ["gtk", "gio", "glib"]

[workspace]
members = [
    "examples/cross_widget",
    "examples/todomvc",
    "crates/itui",
]

exclude = [
    "crates/ui-orbtk",
]

