[package]
name = "caesar"
version = "0.1.0"
authors = ["lee"]
edition = "2018"

[dependencies]
browser = { path = "crates/browser" }
vdom = { path = "crates/vdom" }
tui = { version = "0.5.0", optional = true }
termion = { version = "1.5", optional= true}

[dev-dependencies]
stderrlog = "0.4"
rand = "0.6"
failure = "0.1"
structopt = "0.2"

[workspace]
members = [
    "crates/vdom",
    "crates/browser",
    "crates/browser/examples/simple_app",
    "examples/isomorphic/client",
    "examples/cross_widget",
]

exclude = [
    "crates/ui-orbtk",
]

