[package]
name = "sauron_ui"
version = "0.1.0"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "Commercial"
description = "An html library for building client side webapps"
repository = "https://github.com/ivanceras/sauron"
documentation = "https://docs.rs/sauron"
readme = "README.md"
keywords = ["html", "dom", "web"]
edition = "2018"

publish = false

[dependencies]
sauron = "0.3.0"
sauron_vdom = "0.3.0"
tui = { version = "0.5.0", optional = true }
termion = { version = "1.5", optional= true }
wasm-bindgen = { version = "0.2.42", optional = true }

[dependencies.web-sys]
version = "0.3.19"
optional = true
features = [
    "Comment",
    "console",
    "Document",
    "Element",
    "Event",
    "HtmlElement",
    "EventTarget",
    "KeyboardEvent",
    "HtmlCollection",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "MouseEvent",
    "Node",
    "NodeList",
    "Text",
    "CharacterData",
    "Performance",
    "Window",
]

[dev-dependencies]
stderrlog = "0.4"
rand = "0.6"
failure = "0.1"
structopt = "0.2"
wasm-bindgen-test = "0.2.33"
cfg-if = "0.1.7"



[features]
with-tui = ["tui", "termion"]
with-html = ["web-sys", "wasm-bindgen"]

[workspace]
members = [
    "examples/cross_widget",
]

exclude = [
    "crates/ui-orbtk",
]

[replace]
"sauron:0.3.0" = { path = "../sauron" }
"sauron_vdom:0.3.0" = { path = "../sauron/crates/sauron_vdom" }

