[package]
name = "caesar"
version = "0.1.0"
authors = ["lee"]
edition = "2018"

[workspace]
members = [
    "crates/vdom",
    "crates/browser",
    "crates/browser/examples/simple_app",
    "examples/isomorphic/client",
]

exclude = [
    "crates/ui-orbtk",
]

#[profile.release]
# Tell `rustc` to optimize for small code size.
#opt-level = "s"
