[package]
name = "sauron_ui"
version = "0.1.0"
authors = ["lee"]
edition = "2018"

[dependencies]
sauron = { path = "../sauron" }
sauron_vdom = { path = "../sauron/crates/sauron_vdom" }
tui = { version = "0.5.0", optional = true }
termion = { version = "1.5", optional= true}

[dev-dependencies]
stderrlog = "0.4"
rand = "0.6"
failure = "0.1"
structopt = "0.2"
wasm-bindgen-test = "0.2.33"
cfg-if = "0.1.7"


[features]
with-tui = ["tui", "termion"]

[workspace]
members = [
    "examples/cross_widget",
]

exclude = [
    "crates/ui-orbtk",
]

