[package]
name = "cross_widget"
version = "0.1.0"
authors = ["lee"]
edition = "2018"

[lib]
crate-type = ["cdylib"]


[dependencies]
sauron = "0.10.0"
sauron-native = { path = "../../"}
wasm-bindgen = "0.2.40"
itui = { path = "../../crates/itui" }


[features]
with-html = ["sauron-native/with-html"]
with-tui = ["sauron-native/with-tui"]
with-gtk = ["sauron-native/with-gtk"]

