[package]
name = "cross_widget"
version = "0.1.0"
authors = ["lee"]
edition = "2018"

[lib]
crate-type = ["cdylib"]


[dependencies]
caesar = { path = "../../" }
wasm-bindgen = "0.2.40"
tui = { version = "0.5.0", optional = true }
termion = { version = "1.5", optional= true}
